Repository theforeman/puppet-git, pull requests merged in 2018-07, with the labels that each got.

#39 Support Ubuntu/bionic, drop Fedora 25 & Debian 7
  .travis.yml
  metadata.json
Labels: Needs testing, Not yet reviewed

#40 msync: Acceptance tests update
  Gemfile
  spec/acceptance/nodesets/docker/centos-6.yml
  spec/acceptance/nodesets/docker/centos-7.yml
  spec/acceptance/nodesets/docker/debian-8.yml
  spec/acceptance/nodesets/docker/debian-9.yml
  spec/acceptance/nodesets/docker/ubuntu-14.04.yml
  spec/acceptance/nodesets/docker/ubuntu-16.04.yml
Labels: Modulesync, Needs testing, Not yet reviewed

#41 msync: rake changelog & beaker hostname
  Gemfile
  Rakefile
Labels: Needs testing, Not yet reviewed

#42 Release 4.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing
